# Generated by Django 5.2.12 on 2026-04-16 06:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kurum Adı')),
                ('institution_type', models.CharField(choices=[('university', 'Üniversite'), ('high_school', 'Lise'), ('college', 'Yüksekokul'), ('vocational', 'Meslek Okulu'), ('other', 'Diğer')], default='university', max_length=20, verbose_name='Kurum Tipi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurum',
                'verbose_name_plural': 'Kurumlar',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, verbose_name='Ders Kodu')),
                ('course_name', models.CharField(max_length=255, verbose_name='Ders Adı')),
                ('has_lab', models.BooleanField(default=False, verbose_name='Laboratuvar Bileşeni Var')),
                ('weekly_hours', models.IntegerField(default=2, verbose_name='Haftalık Ders Saati')),
                ('lab_hours', models.IntegerField(default=0, verbose_name='Haftalık Lab Saati')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.department', verbose_name='Bölüm')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'unique_together': {('department', 'course_code')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='scheduler.institution'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=50, verbose_name='Oda Kodu')),
                ('capacity', models.IntegerField(default=30, verbose_name='Kapasite')),
                ('classroom_type', models.CharField(choices=[('LECTURE', 'Derslik'), ('LAB', 'Laboratuvar'), ('COMPUTER_LAB', 'Bilgisayar Laboratuvarı'), ('SEMINAR', 'Seminer Salonu'), ('OTHER', 'Diğer')], default='LECTURE', max_length=20, verbose_name='Sınıf Tipi')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.institution', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Sınıf / Lab',
                'verbose_name_plural': 'Sınıflar / Lablar',
                'unique_together': {('institution', 'room_code')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Sistem Yöneticisi'), ('ADMIN', 'Kurum Yöneticisi'), ('STAFF', 'Personel'), ('IT', 'IT Personeli'), ('LECTURER', 'Öğretim Görevlisi'), ('STUDENT', 'Öğrenci')], default='LECTURER', max_length=20, verbose_name='Rol')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Unvan')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='İlk Girişte Şifre Değiştirmeli')),
                ('plain_password', models.CharField(blank=True, max_length=100, verbose_name='Oluşturulan Şifre (görüntü)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Onaylandı')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.department', verbose_name='Bölüm')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.institution', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Pazartesi'), ('Tuesday', 'Salı'), ('Wednesday', 'Çarşamba'), ('Thursday', 'Perşembe'), ('Friday', 'Cuma')], max_length=10, verbose_name='Gün')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('session_type', models.CharField(choices=[('LECTURE', 'Ders'), ('LAB', 'Laboratuvar')], default='LECTURE', max_length=10, verbose_name='Oturum Tipi')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.classroom', verbose_name='Sınıf / Lab')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.course', verbose_name='Ders')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Hoca / Görevli')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programlar',
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('institution', 'name')},
        ),
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='Gün')),
                ('hour', models.CharField(max_length=15, verbose_name='Saat Dilimi')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Müsait Değil',
                'verbose_name_plural': 'Müsaitlik Dışı Durumlar',
                'unique_together': {('lecturer', 'day', 'hour')},
            },
        ),
    ]
