# Generated by Django 5.2.8 on 2026-06-04 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_coursenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='scheduler.course'),
        ),
    ]
